---
# defaults file for create-ec2

source_path: "/root/ec2-aws/lab-aws"
instance_type: t2.micro
image: ami-00f7e5c52c0f43726
region: us-west-2 # Change the Region
count: 1
subnetid: subnet-078a76439dc81222b
project_name: testing
env: staging
hostpath: "{{ source_path }}/inventory/inventory"
hoststring: "ansible_ssh_user=ec2-user ansible_ssh_private_key_file={{ source_path }}/key-gen/{{ project_name }}-{{ env }}-key.pem"

