---
# defaults file for create-ec2

instance_type: t2.micro
image: ami-00f7e5c52c0f43726
region: us-west-2 # Change the Region
count: 1
subnetid: subnet-01f55070d2c717157
project_name: testing
env: staging
hostpath: /root/lab-aws/inventory/inventory
hoststring: "ansible_ssh_user=ec2-user ansible_ssh_private_key_file=/root/lab-aws/key-gen/aws-private.pem"

