global:
#  slack_api_url: "https://hooks.slack.com/services/SlackWebhookAPI"
  resolve_timeout: 5m
  smtp_require_tls: false
route:
  group_by: ['instance', 'severity']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 5s
  routes:
  - match:
      alertname: InstanceDown
  receiver: 'email'

#receivers:
#- name: 'alert-team'
#  slack_configs:
#  - channel: "#webhook-test"
#    text: "summary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"
receivers:
- name: 'email'
  email_configs:
  - to: 'smtptestssm@gmail.com'
    from: 'smtptestssm@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'smtptestssm@gmail.com'
    auth_identity: 'smtptestssm@gmail.com'
    auth_password: 'tkpuybewxgxqijnn'
