---
- name: Provision an EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: False
  become: true
  vars_files:
  - "{{source_path}}/credential.yaml"

  pre_tasks:
  - name: Installing boto,boto3 python library using Ansible pip module
    pip:
      name: boto,boto3
   
  roles:
  - create-ec2 
  tasks:
  - name: Sleep for 40 seconds and continue with play
    wait_for:
      timeout: 40

- import_playbook: main-node-exporter.yml
- import_playbook: main-prometheuse.yml
- import_playbook: main-grafana.yml
  when: project_name  == "grafana"
 
